spring:
  application:
    name: demo

datasource:
  friend:
    shards:
      - username: root
        password: root
        master:
          name: master-friend
          url: jdbc:mysql://localhost:3307/friend
        slaves:
          - name: slave-friend-1
            url: jdbc:mysql://localhost:3308/friend
      - username: root
        password: root
        master:
          name: master-friend-2
          url: jdbc:mysql://localhost:3309/friend
        slaves:
          - name: slave-friend-2
            url: jdbc:mysql://localhost:3310/friend

sharding:
  friend:
    strategy: MODULAR
    mod: 2