spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cacheaside?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: app
    password: app1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true